name: 'Build Expat'
description: 'Clone and build Expat'
inputs:
  os:
    description: "Runner OS"
    type: string
    default: ''
    required: false

  arch:
    description: "Platform architecture"
    type: string
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Get latest Expat commit hash
      id: expat-hash
      shell: bash
      # NOTE: Pinning libexpat to 2.7.0 as the exact version is not important.
      run: |
        EXPAT_HASH=6d4ffe856df497ac2cae33537665c3fec7ec8a00
        echo "value=$EXPAT_HASH" >> $GITHUB_OUTPUT

    - name: Cache Expat
      id: cache-expat
      uses: actions/cache@v4
      with:
        path: /tmp/install/expat
        key: ${{ inputs.os }}-${{ inputs.arch }}-expat-${{ steps.expat-hash.outputs.value }}

    - name: Build Expat
      if: steps.cache-expat.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone https://github.com/libexpat/libexpat.git /tmp/expat
        cd /tmp/expat/expat
        git checkout ${{ steps.expat-hash.outputs.value }}
        cmake -B build -DEXPAT_BUILD_DOCS=OFF -DEXPAT_BUILD_EXAMPLES=OFF -DEXPAT_BUILD_TESTS=OFF
        cmake --build build --config Release --parallel 4
        cmake --install build --prefix /tmp/install/expat
