name: CI Lint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.18.1
        continue-on-error: true
        with:
          source: '.'
          exclude: './simplepyble ./simpledroidble'
          extensions: 'h,hpp,cpp,c'
          clangFormatVersion: 18
          inplace: False

  cppcheck:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install CppCheck
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y cppcheck
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Run Cppcheck
        run: cppcheck --std=c++17 --error-exitcode=1 --xml --xml-version=2 --force . 2>cppcheck_res.xml
      - name: Generate Report
        if: ${{ failure() }}
        run: cppcheck-htmlreport --title=SimpleBLE --file=cppcheck_res.xml --report-dir=report
      - name: Upload Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report
