name: Build SimpleJavaBLE

on:
  workflow_call:

jobs:
  build-jni-dependencies:
    runs-on: ${{ matrix.config.runner-os || 'ubuntu-latest' }}
    container: ${{ matrix.config.container-image }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, architecture: x64, container-image: dockcross/linux-x64 }
          - { runner-os: ubuntu-22.04, os: linux, architecture: aarch64, container-image: dockcross/linux-arm64 }
          - { runner-os: macos-14, os: macos, architecture: aarch64 } # Containers are not required.
          - { runner-os: windows-2022, os: windows, architecture: x64 } # Containers are not required.

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: ${{ matrix.config.architecture }}

      - name: Build SimpleJavaBLE JNI Wrapper
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simplejavable/cpp"
          build-dir: "$GITHUB_WORKSPACE/build_simplejavable"
          build-config: "Release"
          os: "${{ matrix.config.os }}"
          target-arch: "${{ matrix.config.architecture }}"
          cmake-options: "-DBUILD_SHARED_LIBS=OFF"

      - name: Upload JNI Binaries
        if: matrix.config.os != 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: libsimplejavable_${{ matrix.config.os }}-${{ matrix.config.architecture }}
          path: build_simplejavable/lib/libsimplejavable*

      - name: Upload JNI Binaries
        if: matrix.config.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: libsimplejavable_${{ matrix.config.os }}-${{ matrix.config.architecture }}
          path: build_simplejavable/bin/Release/simplejavable*

  build-jar:
    runs-on: ubuntu-22.04
    needs: build-jni-dependencies
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: "Download JNI Binaries"
        uses: actions/download-artifact@v4
        with:
          pattern: 'libsimplejavable*'
          path: 'jni_download'

      - name: Rename JNI Directories
        working-directory: ${{ github.workspace }}/jni_download
        run: |
          mkdir -p $GITHUB_WORKSPACE/jni
          for dir in libsimplejavable_*; do
            # Extract architecture (e.g., 'x64', 'aarch64' from 'libsimplejavable_linux-x64')
            arch=$(echo "$dir" | sed 's/.*-//')
            target_dir="$GITHUB_WORKSPACE/jni/$arch"
            mkdir -p "$target_dir"
            # Move the contents of the downloaded directory into the target directory
            echo "Moving contents of '$dir' to '$target_dir'"
            mv -v "$dir"/* "$target_dir/"
            # Remove the now-empty source directory
            rmdir "$dir"
          done

      - name: List downloaded files
        run: find $GITHUB_WORKSPACE/jni -type f -ls

      - name: Build SimpleJavaBLE Java Library
        run: |
          gradle -p simplejavable/java -PnativeLibPath=$GITHUB_WORKSPACE/jni -Dorg.gradle.project.buildDir=$GITHUB_WORKSPACE/artifacts --no-daemon build

      - name: List JAR contents
        run: unzip -l artifacts/libs/simplejavable*.jar

      - name: Upload SimpleJavaBLE Java Library
        uses: actions/upload-artifact@v4
        with:
          name: simplejavable.jar
          path: artifacts/libs/simplejavable*.jar