name: CI Smoketest

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-cpp:
    runs-on: ${{ matrix.config.runner-os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, architecture: x64 }
          - { runner-os: macos-14, os: macos, architecture: x64 }
          - { runner-os: macos-14, os: ios, architecture: aarch64 }
          - { runner-os: windows-2022, os: windows, architecture: x64 }
          - { runner-os: ubuntu-22.04, os: android, architecture: armeabi-v7a }

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Build SimpleBLE Library
        uses: ./.github/actions/build-native
        with:
          source-dir: "$GITHUB_WORKSPACE/simpleble"
          build-dir: "$GITHUB_WORKSPACE/build_simpleble"
          install-prefix: "$GITHUB_WORKSPACE/build_simpleble/install"
          build-config: "Release"
          os: "${{ matrix.config.os }}"
          target-arch: "${{ matrix.config.architecture }}"
          cmake-options: "-DBUILD_SHARED_LIBS=OFF"

  build-java:
    runs-on: ubuntu-22.04

    steps:
      - name: Install Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -H apt-get update -y
          sudo -H apt-get install -y libdbus-1-dev

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build SimpleJavaBLE Java Library
        run: |
          gradle -p simplejavable/java -PbuildFromCMake --no-daemon build

  build-python:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { runner-os: ubuntu-22.04, os: linux, arch: native }
          - { runner-os: macos-14, os: macos, arch: native }
          - { runner-os: windows-2022, os: windows, arch: native }

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install dependencies
        run: pip install -r simplepyble/requirements.txt

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: cp312*
          CIBW_BEFORE_ALL_LINUX: "yum update -y && yum group install -y \"Development Tools\" && yum install -y dbus-devel"
          CIBW_ARCHS: ${{ matrix.config.arch }}
          CIBW_SKIP: "*musllinux_* pp* cp36-* cp37-*"
          CIBW_TEST_SKIP: "*"

  build-android-plugins:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Add Version Suffix
        uses: ./.github/actions/setup-version

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build simplebledroidbridge AAR
        run: gradle :bundleReleaseAar -p ./simpledroidbridge --no-daemon -Dorg.gradle.project.buildDir="$GITHUB_WORKSPACE/build_simpledroidbridge"

      - name: List all artifacts
        run: find $GITHUB_WORKSPACE/build_simpledroidbridge -type f -ls